const ROOM_JOINED = "ROOM_JOINED";
const ROOM_LEAVED = "ROOM_LEAVED";
const CALLING = "CALLING";
const INCOMING_CALL = "INCOMING_CALL";
const CALL_ACCEPTED = "CALL_ACCEPTED";

export { ROOM_JOINED, ROOM_LEAVED, CALLING, INCOMING_CALL, CALL_ACCEPTED };
